### ISSUE TITLE
Add marker discovery functionality as described in original publication.

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#1]

**Comment by asmagen** [comment]
Added get.robust.markers function which prioritizes potential marker genes based on multiple expression trends analysis. It creates a marker quality map figure as well.

We probably want to apply it on the dataset presented in the tutorial and show the figure. @Mamie 
diff.exp = get.robust.markers (environment = LCMV1,cluster_group1 = c('Unknown_2','Tcmp'),cluster_group2 = c('CD8','Cycle_CD8'),group1_label = 'Tfh_Tcmp',group2_label = 'CD8')

**Comment by Mamie** [comment]
- [x] add `get.robust.markers` to vignette and README
