### ISSUE TITLE
Printing to console (e.g. print, str) stops working after running ribosomal.score(LCMV1)

### ISSUE THREAD

**Issue by nrachman** [asmagen/robustSingleCell#11]
Session info at start up

```
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2019-04-02                  

Packages ---------------------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.1   2017-07-07 local         
 compiler    3.4.1   2017-07-07 local         
 datasets  * 3.4.1   2017-07-07 local         
 devtools    1.13.4  2017-11-09 CRAN (R 3.4.2)
 digest      0.6.18  2018-10-10 cran (@0.6.18)
 graphics  * 3.4.1   2017-07-07 local         
 grDevices * 3.4.1   2017-07-07 local         
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods   * 3.4.1   2017-07-07 local         
 stats     * 3.4.1   2017-07-07 local         
 tools       3.4.1   2017-07-07 local         
 utils     * 3.4.1   2017-07-07 local         
 withr       2.1.2   2018-03-15 cran (@2.1.2) 

> library(robustSingleCell)
> download_LCMV()
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3423nnn/GSM3423794/suppl//GSM3423794_TotalCD44_1_barcodes.tsv.gz?tool=geoquery'
Content type 'application/x-gzip' length 6840653 bytes (6.5 MB)
==================================================
downloaded 6.5 MB

trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3423nnn/GSM3423794/suppl//GSM3423794_TotalCD44_1_genes.tsv.gz?tool=geoquery'
Content type 'application/x-gzip' length 217849 bytes (212 KB)
==================================================
downloaded 212 KB

trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3423nnn/GSM3423794/suppl//GSM3423794_TotalCD44_1_matrix.mtx.gz?tool=geoquery'
Content type 'application/x-gzip' length 45130443 bytes (43.0 MB)
==================================================
downloaded 43.0 MB

trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3423nnn/GSM3423795/suppl//GSM3423795_TotalCD44_2_barcodes.tsv.gz?tool=geoquery'
Content type 'application/x-gzip' length 2280355 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3423nnn/GSM3423795/suppl//GSM3423795_TotalCD44_2_genes.tsv.gz?tool=geoquery'
Content type 'application/x-gzip' length 217849 bytes (212 KB)
==================================================
downloaded 212 KB

trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3423nnn/GSM3423795/suppl//GSM3423795_TotalCD44_2_matrix.mtx.gz?tool=geoquery'
Content type 'application/x-gzip' length 16055514 bytes (15.3 MB)
==================================================
downloaded 15.3 MB

Data saved at /var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV
[1] 0
> LCMV1 <- initialize.project(datasets = "LCMV1", 
+                             origins = "CD44+ cells",
+                             experiments = "Rep1",
+                             data.path = file.path(tempdir(), "LCMV"),
+                             work.path = file.path(tempdir(), "LCMV/LCMV_analysis"))
> LCMV1 <- read.data(LCMV1, subsample = 500)
Computing
> str(LCMV1)
List of 20
 $ datasets          : chr "LCMV1"
 $ origins           : chr [1:483] "CD44+ cells" "CD44+ cells" "CD44+ cells" "CD44+ cells" ...
 $ experiments       : chr [1:483] "Rep1" "Rep1" "Rep1" "Rep1" ...
 $ labels            :function (object, ...)  
 $ data.path         : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV"
 $ project           : chr "LCMV1"
 $ work.path         : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1"
 $ baseline.work.path: chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1"
 $ res.data.path     : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1/data"
 $ baseline.data.path: chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1/data"
 $ marker.genes      : chr [1:67] "Cd8b1" "Cxcr4" "Ccr7" "Lef1" ...
 $ genes.filter      : Named logi [1:27998] FALSE FALSE FALSE FALSE FALSE FALSE ...
  ..- attr(*, "names")= chr [1:27998] "Xkr4" "Gm1992" "Gm37381" "Rp1" ...
 $ counts            : num [1:12283, 1:483] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
  .. ..$ : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ normalized        : num [1:12283, 1:483] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
  .. ..$ : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ genes             : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
 $ dataset_ids       : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ dataset.labels    : chr [1:483] "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" ...
 $ criteria          : Named logi [1:500] TRUE TRUE TRUE TRUE TRUE TRUE ...
  ..- attr(*, "names")= chr [1:500] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ confounders       :'data.frame':	483 obs. of  2 variables:
  ..$ nUMI  : num [1:483] 4347 5624 5866 11109 5402 ...
  ..$ nGenes: num [1:483] 1703 2197 1937 3206 1988 ...
 $ nsamples          : int 483
> LCMV1 <- get.variable.genes(LCMV1)
Computing
> str(LCMV1)
List of 21
 $ datasets          : chr "LCMV1"
 $ origins           : chr [1:483] "CD44+ cells" "CD44+ cells" "CD44+ cells" "CD44+ cells" ...
 $ experiments       : chr [1:483] "Rep1" "Rep1" "Rep1" "Rep1" ...
 $ labels            :function (object, ...)  
 $ data.path         : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV"
 $ project           : chr "LCMV1"
 $ work.path         : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1"
 $ baseline.work.path: chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1"
 $ res.data.path     : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1/data"
 $ baseline.data.path: chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1/data"
 $ marker.genes      : chr [1:67] "Cd8b1" "Cxcr4" "Ccr7" "Lef1" ...
 $ genes.filter      : Named logi [1:27998] FALSE FALSE FALSE FALSE FALSE FALSE ...
  ..- attr(*, "names")= chr [1:27998] "Xkr4" "Gm1992" "Gm37381" "Rp1" ...
 $ counts            : num [1:12283, 1:483] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
  .. ..$ : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ normalized        : num [1:12283, 1:483] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
  .. ..$ : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ genes             : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
 $ dataset_ids       : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ dataset.labels    : chr [1:483] "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" ...
 $ criteria          : Named logi [1:500] TRUE TRUE TRUE TRUE TRUE TRUE ...
  ..- attr(*, "names")= chr [1:500] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ confounders       :'data.frame':	483 obs. of  2 variables:
  ..$ nUMI  : num [1:483] 4347 5624 5866 11109 5402 ...
  ..$ nGenes: num [1:483] 1703 2197 1937 3206 1988 ...
 $ nsamples          : int 483
 $ HVG               : chr [1:806] "Lman2l" "Wdr75" "Stat1" "1700019D03Rik" ...
> exhaustion_markers <- c('Pdcd1', 'Cd244', 'Havcr2', 'Ctla4', 'Cd160', 'Lag3', 
+                         'Tigit', 'Cd96')
> str(LCMV1)
List of 21
 $ datasets          : chr "LCMV1"
 $ origins           : chr [1:483] "CD44+ cells" "CD44+ cells" "CD44+ cells" "CD44+ cells" ...
 $ experiments       : chr [1:483] "Rep1" "Rep1" "Rep1" "Rep1" ...
 $ labels            :function (object, ...)  
 $ data.path         : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV"
 $ project           : chr "LCMV1"
 $ work.path         : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1"
 $ baseline.work.path: chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1"
 $ res.data.path     : chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1/data"
 $ baseline.data.path: chr "/var/folders/5f/qsvcwhp12yz8272h2jn2y5br0000gn/T//Rtmpk03OkL/LCMV/LCMV_analysis/LCMV1/data"
 $ marker.genes      : chr [1:67] "Cd8b1" "Cxcr4" "Ccr7" "Lef1" ...
 $ genes.filter      : Named logi [1:27998] FALSE FALSE FALSE FALSE FALSE FALSE ...
  ..- attr(*, "names")= chr [1:27998] "Xkr4" "Gm1992" "Gm37381" "Rp1" ...
 $ counts            : num [1:12283, 1:483] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
  .. ..$ : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ normalized        : num [1:12283, 1:483] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
  .. ..$ : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ genes             : chr [1:12283] "Mrpl15" "Lypla1" "Gm37988" "Tcea1" ...
 $ dataset_ids       : chr [1:483] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ dataset.labels    : chr [1:483] "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" "CD44+ cells (Rep1)" ...
 $ criteria          : Named logi [1:500] TRUE TRUE TRUE TRUE TRUE TRUE ...
  ..- attr(*, "names")= chr [1:500] "LCMV1" "LCMV1" "LCMV1" "LCMV1" ...
 $ confounders       :'data.frame':	483 obs. of  2 variables:
  ..$ nUMI  : num [1:483] 4347 5624 5866 11109 5402 ...
  ..$ nGenes: num [1:483] 1703 2197 1937 3206 1988 ...
 $ nsamples          : int 483
 $ HVG               : chr [1:806] "Lman2l" "Wdr75" "Stat1" "1700019D03Rik" ...
> ribosomal.score = ribosomal.score(LCMV1)
> str(LCMV1)
> x <- 1:3
> str(x)
> print(x)
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by nrachman** [comment]
I replicated this issue on another computer with another version of R installed

library(robustSingleCell)
devtools::session_info()

download_LCMV()

LCMV1 <- initialize.project(datasets = "LCMV1", 
                            origins = "CD44+ cells",
                            experiments = "Rep1",
                            data.path = file.path(tempdir(), "LCMV"),
                            work.path = file.path(tempdir(), "LCMV/LCMV_analysis"))

LCMV1 <- read.data(LCMV1, subsample = 1000)

LCMV1 <- get.variable.genes(LCMV1) 
exhaustion_markers <- c('Pdcd1', 'Cd244', 'Havcr2', 'Ctla4', 'Cd160', 'Lag3', 
                        'Tigit', 'Cd96')

ribosomal.score = ribosomal.score(LCMV1)
print("hi") 
str(LCMV1)

The print and str commands don't produce any output to the console.

session info after loading robustSingleCell

devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS Sierra 10.12.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-04-03                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────
 package          * version  date       lib source                                   
 assertthat         0.2.0    2017-04-11 [1] CRAN (R 3.5.0)                           
 backports          1.1.3    2018-12-14 [1] CRAN (R 3.5.0)                           
 bindr              0.1.1    2018-03-13 [1] CRAN (R 3.5.0)                           
 bindrcpp           0.2.2    2018-03-29 [1] CRAN (R 3.5.0)                           
 bitops             1.0-6    2013-08-17 [1] CRAN (R 3.5.0)                           
 callr              3.1.1    2018-12-21 [1] CRAN (R 3.5.0)                           
 caTools            1.17.1.1 2018-07-20 [1] CRAN (R 3.5.0)                           
 cccd               1.5      2015-06-02 [1] CRAN (R 3.5.0)                           
 cli                1.0.1    2018-09-25 [1] CRAN (R 3.5.0)                           
 colorspace         1.4-0    2019-01-13 [1] CRAN (R 3.5.2)                           
 crayon             1.3.4    2017-09-16 [1] CRAN (R 3.5.0)                           
 deldir             0.1-16   2019-01-04 [1] CRAN (R 3.5.2)                           
 desc               1.2.0    2018-05-01 [1] CRAN (R 3.5.0)                           
 devtools           2.0.1    2018-10-26 [1] CRAN (R 3.5.1)                           
 digest             0.6.18   2018-10-10 [1] CRAN (R 3.5.0)                           
 dplyr              0.7.8    2018-11-10 [1] CRAN (R 3.5.0)                           
 FNN                1.1.2.2  2018-12-10 [1] CRAN (R 3.5.0)                           
 fs                 1.2.6    2018-08-23 [1] CRAN (R 3.5.0)                           
 gdata              2.18.0   2017-06-06 [1] CRAN (R 3.5.0)                           
 GGally             1.4.0    2018-05-17 [1] CRAN (R 3.5.0)                           
 ggplot2            3.1.0    2018-10-25 [1] CRAN (R 3.5.0)                           
 ggpubr             0.2      2018-11-15 [1] CRAN (R 3.5.0)                           
 ggrepel            0.8.0    2018-05-09 [1] CRAN (R 3.5.0)                           
 glue               1.3.0    2018-07-17 [1] CRAN (R 3.5.0)                           
 gplots             3.0.1.1  2019-01-27 [1] CRAN (R 3.5.2)                           
 gtable             0.2.0    2016-02-26 [1] CRAN (R 3.5.0)                           
 gtools             3.8.1    2018-06-26 [1] CRAN (R 3.5.0)                           
 igraph             1.2.2    2018-07-27 [1] CRAN (R 3.5.0)                           
 KernSmooth         2.23-15  2015-06-29 [1] CRAN (R 3.5.1)                           
 lazyeval           0.2.1    2017-10-29 [1] CRAN (R 3.5.0)                           
 magrittr           1.5      2014-11-22 [1] CRAN (R 3.5.0)                           
 memoise            1.1.0    2017-04-21 [1] CRAN (R 3.5.0)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 3.5.0)                           
 pillar             1.3.1    2018-12-15 [1] CRAN (R 3.5.0)                           
 pkgbuild           1.0.2    2018-10-16 [1] CRAN (R 3.5.0)                           
 pkgconfig          2.0.2    2018-08-16 [1] CRAN (R 3.5.0)                           
 pkgload            1.0.2    2018-10-29 [1] CRAN (R 3.5.0)                           
 plyr               1.8.4    2016-06-08 [1] CRAN (R 3.5.0)                           
 prettyunits        1.0.2    2015-07-13 [1] CRAN (R 3.5.0)                           
 processx           3.2.1    2018-12-05 [1] CRAN (R 3.5.0)                           
 proxy              0.4-22   2018-04-08 [1] CRAN (R 3.5.0)                           
 ps                 1.3.0    2018-12-21 [1] CRAN (R 3.5.0)                           
 purrr              0.3.0    2019-01-27 [1] CRAN (R 3.5.2)                           
 R6                 2.3.0    2018-10-04 [1] CRAN (R 3.5.0)                           
 RANN               2.6.1    2019-01-08 [1] CRAN (R 3.5.2)                           
 RColorBrewer       1.1-2    2014-12-07 [1] CRAN (R 3.5.0)                           
 Rcpp               1.0.0    2018-11-07 [1] CRAN (R 3.5.0)                           
 remotes            2.0.2    2018-10-30 [1] CRAN (R 3.5.0)                           
 reshape            0.8.8    2018-10-23 [1] CRAN (R 3.5.0)                           
 reshape2           1.4.3    2017-12-11 [1] CRAN (R 3.5.0)                           
 rlang              0.3.1    2019-01-08 [1] CRAN (R 3.5.2)                           
 robustSingleCell * 0.1.0    2019-04-03 [1] Github (asmagen/robustsinglecell@9a5e728)
 rprojroot          1.3-2    2018-01-03 [1] CRAN (R 3.5.0)                           
 rslurm             0.4.0    2017-10-19 [1] CRAN (R 3.5.0)                           
 rstudioapi         0.9.0    2019-01-09 [1] CRAN (R 3.5.2)                           
 scales             1.0.0    2018-08-09 [1] CRAN (R 3.5.0)                           
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 3.5.0)                           
 stringi            1.2.4    2018-07-20 [1] CRAN (R 3.5.0)                           
 stringr            1.4.0    2019-02-10 [1] CRAN (R 3.5.2)                           
 tibble             2.0.1    2019-01-12 [1] CRAN (R 3.5.2)                           
 tidyselect         0.2.5    2018-10-11 [1] CRAN (R 3.5.0)                           
 usethis            1.4.0    2018-08-14 [1] CRAN (R 3.5.0)                           
 withr              2.1.2    2018-03-15 [1] CRAN (R 3.5.0)                           
 yaml               2.2.0    2018-07-25 [1] CRAN (R 3.5.0)                           

[1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library

**Comment by nrachman** [comment]
I think it's an issue with the sink() call in the start() and end() functions from utils.R

https://stackoverflow.com/questions/26495498/rstudio-does-not-display-any-output-in-console-after-entering-code

running closeAllConnections() returns normal print functionally in the console

**Comment by Mamie** [comment]
Thanks, @nrachman! The bug is fixed now for `end()`.
