### ISSUE TITLE
plot.simple.heatmap not exported

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#12]
`plot.simple.heatmap` could be exported for the common use of visualizing user determined marker genes

**Comment by Mamie** [comment]
It was exported but renamed as `plot_simple_heatmap` (to avoid being treated as an S3 method).

**Comment by asmagen** [comment]
Should be mentioned in the tutorial

**Comment by Mamie** [comment]
Added the usage in the vignette and README.
