### ISSUE TITLE
run_tSNE fails on big datasets

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#13]
`sopt <- list(mem = "4GB", time = "0:15:00", share = TRUE)` is hard coded, should be allowed to be provided as input to summarize function.

**Comment by Mamie** [comment]
Added the memory and time limit option to `run_tSNE`.

**Comment by asmagen** [comment]
`run_tSNE` has memory and wall time parameters but is called from `summarize` which doesn't pass these parameters (and run_tSNE is not exported, which is okay).

**Comment by Mamie** [comment]
Added the mem and time option to summarize().
