### ISSUE TITLE
compare.cluster.similarity undefined

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#14]
`compare.cluster.similarity` definition has disappeared from the package.

**Comment by asmagen** [comment]
I see that it appears as `assess.cluster.similarity` but not updated in the tutorial

**Comment by Mamie** [comment]
I don't see uncorrected compare.cluster.similarity. Can you point me to where it is?

**Comment by asmagen** [comment]
It's in the tutorial on the main page of this repository
