### ISSUE TITLE
check_not_slurm is called unnecessarily in function that don't use rslurm

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#16]
Including in read.preclustered.datasets etc

**Comment by Mamie** [comment]
Removed SLURM checking for `read.preclustered.datasets`. What are the other functions?

**Comment by asmagen** [comment]
set/get.cluster.names
plot_simple_heatmap
plot_contour_overlay_tSNE
get.robust.markers
get.robust.cluster.similarity
summarize

**Comment by Mamie** [comment]
Removed the checking statement for these functions.
