### ISSUE TITLE
margins are hard coded in visualize.cluster.cors.heatmaps

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#18]
Figure margins generated by `visualize.cluster.cors.heatmaps` are too short for long cluster names which get truncated in the PDF.
`margin` parameter should solve the issue.

**Comment by Mamie** [comment]
added the margins parameter to the second plot.

**Comment by asmagen** [comment]
Same for `visualize.cluster.similarity.stats` should be valuable (plus showing the correlation values on the heatmap as in previous figures).

**Comment by Mamie** [comment]
Added margins option for visualize.cluster.similarity.stats. How do you add correlation values?

**Comment by asmagen** [comment]
Using `cellnote = cellnote, notecol = "white"` (as in `visualize.cluster.cors.heatmaps`)
