### ISSUE TITLE
Add marker visualizations

### ISSUE THREAD

**Issue by asmagen** [asmagen/robustSingleCell#3]

**Comment by asmagen** [comment]
Added tSNE overlay and flow-like plots.
@Mamie We may want to add an example of using these functions to the tutorial (using the same downsampled dataset you used there).
E.g.:
plot.contour.overlay.tSNE (LCMV1,genes = 'Cd8a')
plot.pair.scatter (LCMV1,gene1 = 'Cxcr5',gene2 = 'Tcf7',cluster_group1 = c('Tfh','Tcmp'),cluster_group2 = c('CD8','Cycle_CD8'),group1_label = 'Tfh_Tcmp',group2_label = 'CD8')

**Comment by Mamie** [comment]
- [x] Add usage of `plot.contour.overlay.tSNE` and `plot.pair.scatter` to vignette and README.Rmd
- [x] fix test-clustering.R to initialize work path in TMPDIR instead of modifying users' home filespace
